name: binder-skeleton
channels:
  - conda-forge
dependencies:
  - fiona
  - geopandas
  - mapclassify
  - matplotlib
  - numpy
  - pandas
  - pathlib
  - pysal
  - requests
  - scipy
  - seaborn
  - shapely
  - tobler
  - xlrd
